//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniEMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caz()
        {
            this.ListaDiagnostics = new HashSet<ListaDiagnostic>();
            this.ListaInvestigaties = new HashSet<ListaInvestigatie>();
            this.Observaties = new HashSet<Observatie>();
            this.Trataments = new HashSet<Tratament>();
        }
    
        public int IdCaz { get; set; }
        public int IdFisa { get; set; }
        public int IdPersonalMedical { get; set; }
        public System.DateTime DataDeschidereCaz { get; set; }
        public Nullable<System.DateTime> DataInchidereCaz { get; set; }
    
        public virtual FisaPacient FisaPacient { get; set; }
        public virtual PersonalMedical PersonalMedical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaDiagnostic> ListaDiagnostics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaInvestigatie> ListaInvestigaties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observatie> Observaties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratament> Trataments { get; set; }
    }
}
