//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniEMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caz()
        {
            this.ListaServiciiMedicales = new HashSet<ListaServiciiMedicale>();
            this.ListaInvestigatiis = new HashSet<ListaInvestigatii>();
            this.ListaObservatiis = new HashSet<ListaObservatii>();
            this.ListaDiagnostices = new HashSet<ListaDiagnostice>();
        }
    
        public int IdCaz { get; set; }
        public string NumarCaz { get; set; }
        public int IdFisa { get; set; }
        public int IdPersonalMedical { get; set; }
        public System.DateTime DataDeschidereCaz { get; set; }
        public Nullable<System.DateTime> DataInchidereCaz { get; set; }
        public string CodDiagnosticPrincipal { get; set; }
    
        public virtual Diagnostic Diagnostic { get; set; }
        public virtual FisaPacient FisaPacient { get; set; }
        public virtual PersonalMedical PersonalMedical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaServiciiMedicale> ListaServiciiMedicales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaInvestigatii> ListaInvestigatiis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaObservatii> ListaObservatiis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaDiagnostice> ListaDiagnostices { get; set; }
    }
}
