//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniEMR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alergie> Alergies { get; set; }
        public virtual DbSet<Caz> Cazs { get; set; }
        public virtual DbSet<Diagnostic> Diagnostics { get; set; }
        public virtual DbSet<FisaPacient> FisaPacients { get; set; }
        public virtual DbSet<Investigatie> Investigaties { get; set; }
        public virtual DbSet<ListaDiagnostic> ListaDiagnostics { get; set; }
        public virtual DbSet<ListaInvestigatie> ListaInvestigaties { get; set; }
        public virtual DbSet<Observatie> Observaties { get; set; }
        public virtual DbSet<Pacient> Pacients { get; set; }
        public virtual DbSet<PersonalMedical> PersonalMedicals { get; set; }
        public virtual DbSet<Tratament> Trataments { get; set; }
    }
}
