//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniEMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaAlergie
    {
        public int IdListaAlergie { get; set; }
        public int IdFisa { get; set; }
        public string CodAlergie { get; set; }
    
        public virtual Alergie Alergie { get; set; }
        public virtual FisaPacient FisaPacient { get; set; }
    }
}
