//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniEMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaServiciiMedicale
    {
        public int IdServiciuMedical { get; set; }
        public int IdCaz { get; set; }
        public string CodServiciu { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Caz Caz { get; set; }
        public virtual ServiciuMedical ServiciuMedical { get; set; }
    }
}
