//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniEMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaCazuri
    {
        public string NumarFisa { get; set; }
        public string CNP { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string NumarCaz { get; set; }
        public System.DateTime DataDeschidereCaz { get; set; }
        public Nullable<System.DateTime> DataInchidereCaz { get; set; }
        public string Inchis { get; set; }
    }
}
