//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniEMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaInvestigatii
    {
        public int IdCaz { get; set; }
        public string CodInvestigatie { get; set; }
        public System.DateTime DataInvestigatie { get; set; }
        public double CostAditional { get; set; }
    
        public virtual Caz Caz { get; set; }
        public virtual Investigatie Investigatie { get; set; }
    }
}
