//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniEMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaportCAS
    {
        public int IdCaz { get; set; }
        public string CodSpital { get; set; }
        public string CNP { get; set; }
        public string NumarCaz { get; set; }
        public Nullable<System.DateTime> DataInchidereCaz { get; set; }
        public string CodDiagnosticPrincipal { get; set; }
        public Nullable<int> LunaInchidereCaz { get; set; }
        public Nullable<int> AnInchidereCaz { get; set; }
        public string CodInvestigatie { get; set; }
        public Nullable<double> CostAditionalInvestigatie { get; set; }
        public string CodServiciuMedical { get; set; }
        public Nullable<double> CostAditionalServicuMedical { get; set; }
    }
}
